### ISSUE TITLE
Fix another test in Login.test.js

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-frontend#10]
## Issue

Please troubleshoot the test on line 73 of Login.test.js. You can replace the .skip snippet at the beginning of the text declaration to .only, and run the test using `npm run test Login`.

Test should ensure that clicking on the "Sign Up" button makes the text of the same button change to "Sign In". I'm not sure why it isn't working! Please take a look and see if you can figure it out.

## Additional Resources

You may find it helpful to read the docs on [testing Apollo/GraphQL](https://www.apollographql.com/docs/react/development-testing/testing/).

**Comment by guptabhaskar** [comment]
@capndave Can you review this? #12
