### ISSUE TITLE
Limit Button component to a width of no more than 264px, padding included

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-frontend#18]
Add a `width` property to the `StyledButton` declaration at line 5 of `Button.js`. Ensure that the rendered button is no more wide than 264px, including padding.

**Comment by roygrv21** [comment]
Can I take this task?

**Comment by saranshkotnala** [comment]
can i be assigned this task

**Comment by karans5004** [comment]
@capndave : Raised a PR #19  for same, pl review and let me know if any changes needed.

**Comment by capndave** [comment]
@roygrv21 I'm assigning this to you since you're the first person that volunteered
