### ISSUE TITLE
Make Navbar visible only if user is validated

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-frontend#2]
Make navbar (not the whole header, just the nav links) visible only if user is validated

**Comment by urguru** [comment]
Heyy Can I Pick up this and work on it

**Comment by capndave** [comment]
Yes please! Thanks. If you're using the API to test, let me know if you
need help getting the API up and running.

**Comment by paytonagreen** [comment]
I can get this one!

**Comment by paytonagreen** [comment]
Got this sorted, #14 !
