### ISSUE TITLE
Update AddGarden Component

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-frontend#21]
Please update the AddGarden component in the following way:

- Remove the submit button
- On a mobile view, the plus icons should appear to the right of the input element and act as the submit button (it shouldn't toggle the view)
- On a desktop view the submit button should be used. Please place it to the right of the input element.
- At the top of the html/jsx, there should be either a subcomponent or a declaration of the following:
  a. An arrow icon (see c, below) `FaChevronDown` icon and text saying "Add Garden". You can add the icon(s) using `import { FaChevronDown } from "react-icons/fa`
  b. On click, it should toggle `formVisible`.
  c. When `formVisible` is true, the component should display the `FaChevronRight`. If `formVisible` is false, show `FaChevronDown`.

## Extra Credit

If you want to be extra awesome, feel free to add some tests for the component. You can do those in a separate pull request if you prefer.

**Comment by fernandoamz** [comment]
May I take this one?

**Comment by capndave** [comment]
@fernandoamz Go for it! Thanks.

**Comment by fernandoamz** [comment]
Could you update the tags? It will change from October 3rd https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by paytonagreen** [comment]
I can work on this today!
