### ISSUE TITLE
Ensure that results of GET_USER_GARDENS query updates the GardenList appropriately

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-frontend#26]
Query currently runs on load and doesn't update the view when it completes. Please update to populate the view with query results asyncronously

**Comment by mgilberties** [comment]
Can I have a go at this please?

**Comment by mgilberties** [comment]
@capndave Pulled the repo down, installed and started no problem, but unable to sign up. Do you have any idea how I can authenticate?

**Comment by capndave** [comment]
Did you get any kind of error message? Try adding a `.env` file in the project root and add `REACT_APP_GRAPHQL_SERVER="https://gardenbuilder-backend.uc.r.appspot.com/graphql/"` to it.

**Comment by mgilberties** [comment]
@capndave UI states: 'Unable to sign in' network panel request shows a 200 with: `
data: {tokenAuth: null}
errors: [{message: "Please enter valid credentials", locations: [{line: 2, column: 3}], path: ["tokenAuth"]}]` as the response body. Even after adding the env var.

**Comment by mgilberties** [comment]
I think this is the actual error stopping me from signing up:

`{,…}
data: {createUser: null}
errors: [{message: "Error decoding signature", locations: [{line: 2, column: 3}], path: ["createUser"]}]
0: {message: "Error decoding signature", locations: [{line: 2, column: 3}], path: ["createUser"]}
locations: [{line: 2, column: 3}]
0: {line: 2, column: 3}
message: "Error decoding signature"
path: ["createUser"]
0: "createUser"`

**Comment by capndave** [comment]
Ok looking into it now

**Comment by mgilberties** [comment]
Thank you.

**Comment by capndave** [comment]
Here's a long shot: Try making sure your password:
- Is 6 letters long or more
- Has a capitol letter in it
- Has one or more punctuation marks/symbols

**Comment by capndave** [comment]
I'm unable to replicate on my end but I see that a DecodeError was thrown on the back end.

**Comment by capndave** [comment]
From this [Smashing Magazine article](https://www.smashingmagazine.com/2020/02/django-highlights-user-models-authentication/#:~:text=User%20passwords%20are%20required%20to,stock%20forms%20validate%20these%20requirements.):

User passwords are required to be at least 8 characters, not entirely numbers, not match too closely to the username, and not be on a list of the 20,000 most common passwords. The Django stock forms validate these requirements.

**Comment by mgilberties** [comment]
@capndave Thanks  for your help, I managed to create a user account and login, but only by applying the queries via GraphiQL and then hit up against some other errors. I think I'm about out of my depth on this one, not that clued up on GraphQL. I will put this one back up for grabs

**Comment by LucianoVirmes** [comment]
I can work on it. @capndave can you assign it me?

**Comment by capndave** [comment]
Assigning it to @LucianoVirmes now.

**Comment by capndave** [comment]
@mgilberties you said you wanted to do some design work. Do you have access to some design software? I can send you screen shots of what we have so far if you want, I'd love some design help.

**Comment by LucianoVirmes** [comment]
@capndave Im getting this error when I run the query: `Error: column beds_bed.name does not exist` is the database updated?

**Comment by capndave** [comment]
Maybe something is wrong in `beds/model.py`? Either that or it needs a fresh migration. I'll look into it, thanks for letting me know!

**Comment by LucianoVirmes** [comment]
OK, let me know when it's working, then I can back to work.

**Comment by capndave** [comment]
Ok I think this is fixed now, please give it another try!

**Comment by paytonagreen** [comment]
Fixed with #44
