### ISSUE TITLE
Make a basic Bed component

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-frontend#33]
## Type
Feature request

## Problem or To-Do
Make a basic bed component. It should include:
- [ ] Three `select` elements that allow you to set the width, height, and measuring units (feet or cm) of a bed, in feet.
- [ ] A grid view (using css grid) that renders the correct number of squares according to the dimensions above. If a bed is 3'x5', for example, the grid should have 3 columns and 5 rows.
- [ ] If cm are selected, please ensure that each cell of the grid represents 30cm.

## Additional Information
Later we will include functionality to populate each cell of the grid with fruits or vegetables. It will be something a bit similar to the [Gardeners Supply Company tool](https://www.gardeners.com/on/demandware.store/Sites-Gardeners-Site/default/KGP-Design). Don't worry about adding that functionality now.

**Comment by edwinmunguia** [comment]
I would like to contribute to the project. assign me this TODO
