### ISSUE TITLE
Docs Add: Code_of_conduct and Contributor Guidelines

### ISSUE THREAD

**Issue by orama254** [capndave/gardenbuilder-frontend#34]
## Type
support request

## Problem or To-Do
Add code of conduct, contributor guidelines and license file to align with Github's [recommended community standards](https://opensource.guide/)

## Environment
N/A (not applicable)

## Additional Information
**screenshot**
![community profile_gardenbuilder-frontend](https://user-images.githubusercontent.com/50571688/95051481-fd381f80-06f5-11eb-9f57-6eba95fb1624.JPG)

I'd be delighted to take up this issue if needed

**Comment by capndave** [comment]
Awesome! Thanks for taking this on.
