### ISSUE TITLE
Remove compile time warnings.

### ISSUE THREAD

**Issue by roygrv21** [capndave/gardenbuilder-frontend#38]
## Type
Enhancement

## Problem or To-Do
There are many compile-time warnings. I want to remove the warnings without affecting the flow of the application.
![image](https://user-images.githubusercontent.com/36206378/95379817-81abbd80-0903-11eb-8156-79d7ef7175ad.png)

## Effects of the problem
The application could become slow based on the warnings, as more and more waring keeps on accumulating.

**Comment by roygrv21** [comment]
@capndave I think this issue might slow down the performance and also it makes the console very messy. What is your opinion?
If you agree with it, can I work on it?

**Comment by paytonagreen** [comment]
@capndave and I were just talking about this the other day. These are warnings that create-react-app always auto-generates for any unused vars. Seems intended to prevent any unintentional memory drain, but it's super annoying in development! I think the easy fix is going through and deleting any declarations we definitely won't need and commenting others out, but I personally would definitely love a permanent fix.

**Comment by roygrv21** [comment]
@paytonagreen One simple solution would be developers should check such kind of warnings before committing the final piece of code. I know this is not a permanent solution, but we can follow it.

**Comment by paytonagreen** [comment]
@roygrv21 I think that is almost too reasonable! If you want to clean these up, I think it would be very welcome. Maybe we can update the contribution guidelines and/or the CI/CD (once that's set up) to make sure we don't keep passing these along.

**Comment by capndave** [comment]
Thanks for working on cleaning these up! We're working on setting up linting/autoformatting in a CI pipeline/github actions. There's probably a `no-unused-variables` rule we can set for that.
