### ISSUE TITLE
Fix test in Login.js

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-frontend#9]
## Problem

Please troubleshoot the test on line 91 of `Login.test.js`. You can replace the `.skip` snippet at the beginning of the text declaration to `.only`, and run the test using `npm run test Login`  Test should ensure that signing up makes the app reroute to the gardens page. I'm not sure why it isn't working! Please take a look and see if you can figure it out.

## Additional Resources

You may find it helpful to read the docs on [testing Apollo/GraphQL](https://www.apollographql.com/docs/react/development-testing/testing/).

**Comment by guptabhaskar** [comment]
Can you review this @capndave
